name: Spin Up Test DB
description: Builds a docker image and pushes to a remote registry
inputs:
  db_url:
    description: Databse Url
    required: true
  infra_repo_key:
    description: Secret Key
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        repository: TeleVet/db-sdk-prisma2
        path: db-sdk-prisma2
        ssh-key: ${{ inputs.infra_repo_key }}

    - shell: bash
      run: |
        npm i
        npx prisma migrate dev
      working-directory: db-sdk-prisma2
      env:
        DATABASE_URL: ${{ inputs.db_url }}
