name: Spin Up Test DB
description: Builds a docker image and pushes to a remote registry
inputs:
  infra_repo_key:
    description: Secret Key
    required: true
  branch:
    description: Branch to pull from
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        repository: TeleVet/db-sdk-prisma2
        path: db-sdk-prisma2
        ssh-key: ${{ inputs.infra_repo_key }}
        ref: ${{ inputs.branch }}

    - shell: bash
      run: |
        npm i
        npx prisma migrate dev --skip-generate
      working-directory: db-sdk-prisma2

    - uses: actions/checkout@v2
      with:
        repository: TeleVet/pawblisher
        path: pawblisher
        ssh-key: ${{ inputs.infra_repo_key }}
        ref: ${{ inputs.branch }}
        
    - shell: bash
      run: |
        npm i --legacy-peer-deps
        npm run content:reset-db
      working-directory: pawblisher
