name: Spin Up Test DB
description: Builds a docker image and pushes to a remote registry
inputs:
  infra_repo_key:
    description: Secret Key
    required: true
  branch:
    description: Branch to pull from
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        repository: TeleVet/db-sdk-prisma2
        path: db-sdk-prisma2
        ssh-key: ${{ inputs.infra_repo_key }}
        ref: ${{ inputs.branch }}

    - shell: bash
      run: |
        npm i
        npx prisma migrate resolve --applied 20230310152605_drop_enable_push_field
        npx prisma migrate dev
        npx prisma db seed
      working-directory: db-sdk-prisma2
