name: Authenticate AWS Tools
description: Authenticates AWS tooling for use in the rest of the workflow
inputs:
  role-to-assume:
    description: ARN of the role to assume
    required: true
  role-session-name:
    description: Name to use for role session
    required: true
  region:
    description: AWS region to use
    required: true
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.region }}
        role-session-name: ${{ inputs.role-session-name }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1