name: Build and Push Docker Image
description: Builds a docker image and pushes to a remote registry
inputs:
  tags:
    description: Same as the `tags` input on the [Docker Metadata](https://github.com/docker/metadata-action#tags-input) action.
    required: false
    default: |
      type=sha,format=long
      type=ref,event=branch
  build_args:
    description: Same as the `build-args` input on the [Docker Build and Push](https://github.com/docker/build-push-action#build-args-input) action.
    required: false
    default: ""
  registry:
    description: Registry for image
    required: true
  image_name:
    description: Name for image
    required: true
runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: ${{ inputs.tags }}

    - name: add dummy firebase
      shell: bash
      run: |
        echo "{}" > firebase.dummy.json

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        build-args: ${{ inputs.build_args }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha, mode=max
        platforms: linux/amd64,linux/arm64
