name: Docker Build & Push

on:
  workflow_call:
    inputs:
      role-to-assume:
        type: string
        description: ARN of the role to assume
        required: true
      role-session-name:
        type: string
        description: Name to use for role session
        required: true
      region:
        type: string
        description: AWS region to use
        required: true
      registry:
        type: string
        description: Registry for image
        required: true
      image_name:
        type: string
        description: Name for image
        required: true
    secrets:
      build_args:
        description: Same as the `build-args` input on the [Docker Build and Push](https://github.com/docker/build-push-action#build-args-input) action.
        required: false

env:
  APP_NAME: ${{ inputs.app_name }}
  IMAGE_REPO: ${{ inputs.registry }}/${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate AWS Tools
        uses: televet/actions-workflows/.github/actions/aws-auth@main
        with:
          role-session-name: ${{ inputs.role-session-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        uses:  televet/actions-workflows/.github/actions/docker-build@feat/multi-arch
        with:
          registry: ${{ inputs.registry }}
          image_name: ${{ inputs.image_name }}
          build_args: ${{ secrets.build_args }}
          platform: linux/amd64
          tags: |
            type=ref,event=branch,suffix=-amd64
            type=sha,format=long,suffix=-amd64
            type=ref,event=tag,suffix=-amd64
  
  docker-arm64:
    runs-on:
      - self-hosted
      - linux
      - arm64
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate AWS Tools
        uses: televet/actions-workflows/.github/actions/aws-auth@main
        with:
          role-session-name: ${{ inputs.role-session-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        uses:  televet/actions-workflows/.github/actions/docker-build@feat/multi-arch
        with:
          registry: ${{ inputs.registry }}
          image_name: ${{ inputs.image_name }}
          build_args: ${{ secrets.build_args }}
          platform: linux/arm64
          tags: |
            type=ref,event=branch,suffix=-arm64
            type=sha,format=long,suffix=-arm64
            type=ref,event=tag,suffix=-arm64

  docker-manifest:
    needs: [docker-arm64, docker-amd64]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate AWS Tools
        uses: televet/actions-workflows/.github/actions/aws-auth@main
        with:
          role-session-name: ${{ inputs.role-session-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract ARM64 Image Digest
        id: extract-digest-arm64
        run: |
          aws ecr batch-get-image --repository-name ${{ inputs.image_name }} --image-ids imageTag=sha-${{ github.sha }}-arm64 > output.json
          ARM64_DIGEST=$(jq -r '.images[0].imageManifest | fromjson | .manifests[] | select(.platform.architecture=="arm64") | .digest' output.json)
          echo "ARM64_DIGEST=$ARM64_DIGEST" >> $GITHUB_ENV

      - name: Extract AMD64 Image Digest
        id: extract-digest-amd64
        run: |
          aws ecr batch-get-image --repository-name ${{ inputs.image_name }} --image-ids imageTag=sha-${{ github.sha }}-amd64 > output.json
          AMD64_DIGEST=$(jq -r '.images[0].imageManifest | fromjson | .manifests[] | select(.platform.architecture=="amd64") | .digest' output.json)
          echo "AMD64_DIGEST=$AMD64_DIGEST" >> $GITHUB_ENV

      - name: Docker Create Manifest
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          echo "==> Creating Manifest!!!" 
          docker manifest create ${{ inputs.registry }}/${{ inputs.image_name }}:multi-arch-manifest ${{ inputs.registry }}/${{ inputs.image_name }}@$ARM64_DIGEST ${{ inputs.registry }}/${{ inputs.image_name }}@$AMD64_DIGEST
          echo "DONE!!!"

          echo "==> Starting Annotations!!!"
          docker manifest annotate ${{ inputs.registry }}/${{ inputs.image_name }}:multi-arch-manifest ${{ inputs.registry }}/${{ inputs.image_name }}@$ARM64_DIGEST --os linux --arch arm64
          docker manifest annotate ${{ inputs.registry }}/${{ inputs.image_name }}:multi-arch-manifest ${{ inputs.registry }}/${{ inputs.image_name }}@$AMD64_DIGEST --os linux --arch amd64
          echo "DONE!!!"

          echo "==> Pushing Manifest!!!"
          docker manifest push ${{ inputs.registry }}/${{ inputs.image_name }}:multi-arch-manifest
          echo "DONE!!!"
