name: Docker Build & Push

on:
  workflow_call:
    inputs:
      role-to-assume:
        type: string
        description: ARN of the role to assume
        required: true
      role-session-name:
        type: string
        description: Name to use for role session
        required: true
      region:
        type: string
        description: AWS region to use
        required: true
      registry:
        type: string
        description: Registry for image
        required: true
      image_name:
        type: string
        description: Name for image
        required: true
    secrets:
      build_args:
        description: Same as the `build-args` input on the [Docker Build and Push](https://github.com/docker/build-push-action#build-args-input) action.
        required: false

env:
  APP_NAME: ${{ inputs.app_name }}
  IMAGE_REPO: ${{ inputs.registry }}/${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
  docker-amd64:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate AWS Tools
        uses: televet/actions-workflows/.github/actions/aws-auth@main
        with:
          role-session-name: ${{ inputs.role-session-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        uses:  televet/actions-workflows/.github/actions/docker-build@feat/multi-arch
        with:
          registry: ${{ inputs.registry }}
          image_name: ${{ inputs.image_name }}
          build_args: ${{ secrets.build_args }}
          platform: linux/amd64
          tags: |
            type=sha,format=long,suffix=-amd64
  
  docker-arm64:
    runs-on:
      - self-hosted
      - linux
      - arm64
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate AWS Tools
        uses: televet/actions-workflows/.github/actions/aws-auth@main
        with:
          role-session-name: ${{ inputs.role-session-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker Image
        uses:  televet/actions-workflows/.github/actions/docker-build@feat/multi-arch
        with:
          registry: ${{ inputs.registry }}
          image_name: ${{ inputs.image_name }}
          build_args: ${{ secrets.build_args }}
          platform: linux/arm64
          tags: |
            type=sha,format=long,suffix=-arm64
