name: QA Deployment

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        description: Name of the app that is being updated.
        required: true
      image_tag:
        type: string
        description: Image tag that should be deployed to qa.
        required: true
      role-to-assume:
        type: string
        description: ARN of the role to assume
        required: true
      role-session-name:
        type: string
        description: Name to use for role session
        required: true
      region:
        type: string
        description: AWS region to use
        required: true
      registry:
        type: string
        description: Registry for image
        required: true
      image_name:
        type: string
        description: Name for image
        required: true
      infra_repo:
        type: string
        description: Name of the infrastructure repo
        required: false
        default: infrastructure
    secrets:
      infra_repo_key:
        required: true
      e2e_repo_access_token:
        required: false
      build_args:
        description: Same as the `build-args` input on the [Docker Build and Push](https://github.com/docker/build-push-action#build-args-input) action.
        required: false

env:
  APP_NAME: ${{ inputs.app_name }}
  IMAGE_REPO: ${{ inputs.registry }}/${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
  qa-deployment-build:
    uses: televet/actions-workflows/.github/workflows/docker-build.yaml@feat/multi-arch
    with:
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name }}
      region: ${{ inputs.region }}
      registry: ${{ inputs.registry }}
      image_name: ${{ inputs.image_name }}
      image_tags: |
        type=ref,event=pr
        type=raw,value=sha-${{ github.event.pull_request.head.sha }}
    secrets:
      build_args: |
        NPM_TOKEN=${{ secrets.NPM_TOKEN }}

  qa-deployment:
    needs: qa-deployment-build
    uses: televet/actions-workflows/.github/workflows/reusable-qa-deploy.yaml@feat/multi-arch
    with:
      app_name: ${{ inputs.app_name }}
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: ${{ inputs.role-session-name }}
      region: ${{ inputs.region }}
      infra_repo: ${{ inputs.infra_repo }}
    secrets:
      infra_repo_key: ${{ secrets.INFRA_REPO_KEY }} 
      e2e_repo_access_token: ${{ secrets.E2E_REPO_ACCESS_TOKEN }}