name: Docker Tag Releases

on:
  workflow_call:
    inputs:
      role-to-assume:
        type: string
        description: ARN of the role to assume
        required: true
      role-session-name:
        type: string
        description: Name to use for role session
        required: true
      region:
        type: string
        description: AWS region to use
        required: true
      registry:
        type: string
        description: Registry for image
        required: true
      image_name:
        type: string
        description: Name for image
        required: true
      image_tags:
        type: string
        required: false
        default: |
          type=ref,event=tag
          type=ref,event=tag,suffix=-${{ github.run_number }}

env:
  APP_NAME: ${{ inputs.app_name }}
  IMAGE_REPO: ${{ inputs.registry }}/${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
  release-tag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Authenticate AWS Tools
        uses: televet/actions-workflows/.github/actions/aws-auth@main
        with:
          role-session-name: ${{ inputs.role-session-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check and Tag Image with Commit SHA
        run: |
          COMMIT_SHA="sha-$(git rev-parse ${{ github.ref }})"
          IMAGE_META="$(aws ecr describe-images --repository-name=${{ inputs.image_name }} --image-ids=imageTag=$COMMIT_SHA 2> /dev/null)"

          if [[ $? == 0 ]]; then
            echo "Image with commit SHA $COMMIT_SHA found."

            IMAGE_MANIFEST=$(aws ecr batch-get-image --repository-name ${{ inputs.image_name }} --image-ids imageTag=$COMMIT_SHA --query 'images[].imageManifest' --output text)

            RELEASE_TAG=${{ github.ref_name }}
            aws ecr put-image --repository-name ${{ inputs.image_name }} --image-tag "$RELEASE_TAG" --image-manifest "$IMAGE_MANIFEST"
          else
            echo "Image with commit SHA $COMMIT_SHA not found."
            exit 1
          fi
