name: QA Deployments Reusable Workflow

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        description: Name of the app that is being updated.
        required: true
      role-to-assume:
        type: string
        description: ARN of the role to assume
        required: true
      role-session-name:
        type: string
        description: Name to use for role session
        required: true
      region:
        type: string
        description: AWS region to use
        required: true
      infra_repo:
        type: string
        description: Name of the infrastructure repo
        required: false
        default: infrastructure
    secrets:
      infra_repo_key:
        required: true
      e2e_repo_access_token:
        required: false

jobs:
  qa-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate AWS Tools
        uses: televet/actions-workflows/.github/actions/aws-auth@main
        with:
          role-session-name: ${{ inputs.role-session-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          region: ${{ inputs.region }}

      - name: Select QA Environment
        id: select-qa-env
        uses: moonswitch/select-qa-env@v0.3.3
        with:
          cloud_provider: aws
          table: qa-envs

      - name: Checkout infrastructure repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.infra_repo }}
          ssh-key: ${{ secrets.infra_repo_key }}
          path: infrastructure

      - name: Create QA deployment config file
        env:
          QA_LANE: ${{ steps.select-qa-env.outputs.env_name }}
          QA_FILE: ${{ steps.select-qa-env.outputs.env_name }}.json
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_REPO: ${{ github.repository }}
          URL: ${{ steps.select-qa-env.outputs.url }}
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 60
          max_attempts: 5
          retry_on: error
          command: |-
            cd ${GITHUB_WORKSPACE}/infrastructure/qa-envs
            ./qa_apps.sh add
            
            if [ -s "${QA_FILE}" -a -s "qa_lanes.libsonnet" ]; then
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add . && git diff --cached --quiet || \
                git commit -m "[ci] Deploy PR-${{ github.event.number }} from ${{ github.repository }}" && \
                git push && \
                git status --porcelain
              echo "QA file has been updated and pushed."
            else
              echo "${QA_FILE} or qa_lanes.libsonnet is empty. Aborting job."
              exit 1
            fi
      
      - name: Create QA Deployment
        uses: altinukshini/deployment-action@v1.2.6
        id: deployment
        with:
          pr: true
          pr_id: ${{ github.event.number }}
          transient_environment: true
          token: "${{ github.token }}"
          target_url: https://${{ steps.select-qa-env.outputs.url }}
          environment: ${{ steps.select-qa-env.outputs.env_name }}
          initial_status: success
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Clinic Web Automation Tests
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.repository == 'TeleVet/clinic-web' }}
        with:
          token: ${{ secrets.e2e_repo_access_token }}
          repository: TeleVet/e2e-tests
          event-type: clinic-web-automated-test-isolated
          client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "repository": "clinic-web", "user": "${{ github.actor }}", "qa_lane": "${{ steps.select-qa-env.outputs.env_name }}"}'

      - name: Run Care Web Automation Tests
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.repository == 'TeleVet/care-web' }}
        with:
          token: ${{ secrets.e2e_repo_access_token }}
          repository: TeleVet/e2e-tests
          event-type: care-web-automated-test-isolated
          client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "repository": "care-web", "user": "${{ github.actor }}", "qa_lane": "${{ steps.select-qa-env.outputs.env_name }}"}'

      - name: Run Core Api Automation Tests
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.repository == 'TeleVet/core-api' }}
        with:
          token: ${{ secrets.e2e_repo_access_token }}
          repository: TeleVet/e2e-tests
          event-type: core-api-automated-test-isolated
          client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "repository": "core-api", "user": "${{ github.actor }}", "qa_lane": "${{ steps.select-qa-env.outputs.env_name }}"}'

      - name: Run Core Jobs Automation Tests
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.repository == 'TeleVet/core-jobs' && inputs.app_name == 'core-jobs-sqs-model-changed' }}
        with: 
          token: ${{ secrets.e2e_repo_access_token }}
          repository: TeleVet/e2e-tests
          event-type: core-jobs-automated-test-isolated
          client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "repository": "core-jobs", "user": "${{ github.actor }}", "qa_lane": "${{ steps.select-qa-env.outputs.env_name }}"}'

      - name: Run Payments Api Automation Tests
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.repository == 'TeleVet/payments-api' && inputs.app_name == 'payments-jobs' }}
        with:
          token: ${{ secrets.e2e_repo_access_token }}
          repository: TeleVet/e2e-tests
          event-type: payments-api-automated-test-isolated
          client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "repository": "payments-api", "user": "${{ github.actor }}", "qa_lane": "${{ steps.select-qa-env.outputs.env_name }}"}'