name: Spin Up Test DB
description: Builds a docker image and pushes to a remote registry
inputs:
  infra_repo_key:
    description: Secret Key
    required: true
  branch:
    description: Branch to pull from
    required: false
  lane:
    description: lane to pull images from
    required: false
runs:
  using: composite
  steps:
    - name: Authenticate AWS Tools
      uses: televet/actions-workflows/.github/actions/aws-auth@main
      with:
        role-session-name: github-actions-clinic-web
        role-to-assume: arn:aws:iam::400390564163:role/github-actions-role-Role-1O13C3B2W9PE2
        region: us-east-2

    - uses: actions/checkout@v2
      with:
        repository: TeleVet/infrastructure
        path: infrastructure
        ssh-key: ${{ inputs.infra_repo_key }}
        ref: ${{ inputs.branch }}

    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1.4.1

    - name: Spin up local infrastructure and sleep
      shell: bash
      run: |
        npm i ts-node
        npm i
        sh decryptLocalServiceEnvs.sh
        LANE=${{ inputs.lane }} npx ts-node local/getQaLaneDeployments.ts
        docker-compose up -d
        sleep 60
        docker stats -a --no-stream
        docker logs infrastructure_core-api_1
        sleep 60
        docker stats -a --no-stream
        docker logs infrastructure_core-api_1

      working-directory: infrastructure
